version: "3.8"

networks:
    default:
        external: true
        name: "bankNetwork"

services:
    nginx:
        image: nginx:stable
        container_name: bank-web
        ports:
            - 8080:80
        volumes:
            - .:/var/www/bank_app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

        depends_on:
            - php
        restart: unless-stopped

    php:
        build:
            context: ./docker
            dockerfile: DockerFile
        container_name: bank-php
        volumes:
            - .:/var/www/bank_app
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped
